[package]
name = "ingotd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ingotd"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde_json.workspace = true
ingot-server.workspace = true
ingot-store.workspace = true
ingot-runtime.workspace = true
ingot-network.workspace = true
ingot-volume.workspace = true
ingot-util.workspace = true
ingot-api.workspace = true
nix.workspace = true
libc.workspace = true
