[package]
name = "ingot-server"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
axum.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
futures.workspace = true
bytes.workspace = true
percent-encoding.workspace = true
libc.workspace = true
base64.workspace = true
chrono.workspace = true
ingot-util.workspace = true
ingot-api.workspace = true
ingot-store.workspace = true
ingot-image.workspace = true
ingot-runtime.workspace = true
ingot-network.workspace = true
ingot-volume.workspace = true
ingot-registry.workspace = true
ingot-builder.workspace = true
flate2.workspace = true
tar.workspace = true
tempfile.workspace = true
