[package]
name = "ingot-network"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
rtnetlink.workspace = true
netlink-packet-route.workspace = true
futures.workspace = true
libc.workspace = true
ingot-util.workspace = true
ingot-api.workspace = true
ingot-store.workspace = true
